<?php session_start();

require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'init.cfg.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'self.cfg.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'rel.cfg.php';

//require INC_DBPDO_FILE_PATH;

require BASE_DIR.FILE_INF;