<?php session_start();
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'init.cfg.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'self.cfg.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'rel.cfg.php';


require INC_DBPDO_FILE_PATH;

if (file_exists(BASE_DIR.DIR_OPS.DIR_MDL.$_POST['m'].DIRECTORY_SEPARATOR.$_POST['f'].POSTFIX_MDL) && !is_dir(BASE_DIR.DIR_OPS.DIR_MDL.$_POST['m'].DIRECTORY_SEPARATOR.$_POST['f'].POSTFIX_MDL)) {
			//	require BASE_DIR.DIR_OPS.NAME_FILE_ROUTER;
	require BASE_DIR.DIR_OPS.DIR_MDL.$_POST['m'].'/'.$_POST['f'].POSTFIX_MDL;
	//$return_arr[0][0]=BASE_DIR.DIR_OPS.DIR_COMM.DIR_INC.OPS_INC_RETURN.POSTFIX_INC;
	//require BASE_DIR.DIR_OPS.DIR_COMM.DIR_INC.OPS_INC_RETURN.POSTFIX_INC;
}else{
	$return_arr[NAME_APP_404]=URL_BASE.NAME_FILE_INF.DIRECTORY_SEPARATOR.NAME_APP_404;
}

require BASE_DIR.DIR_OPS.DIR_COMM.DIR_INC.OPS_INC_RETURN.POSTFIX_INC;

//$return_arr[0][0]=BASE_DIR.DIR_OPS.DIR_COMM.DIR_MDL.$_POST['m'].'/'.$_POST['f'].POSTFIX_MDL;
////$return_arr[0][0]=$app_base_dir.$dir_mdl.$_POST['m'];
//

//Header("Location: ".URL_BASE.NAME_FILE_INF.'/'.NAME_APP_404);