<?php session_start();

require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'init.cfg.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'self.cfg.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'comm'.DIRECTORY_SEPARATOR.'cfg'.DIRECTORY_SEPARATOR.'rel.cfg.php';

require BASE_DIR.NAME_COMM.DIRECTORY_SEPARATOR.NAME_INC.DIRECTORY_SEPARATOR.INC_DBPDO.POSTFIX_INC;

if (!isset($_POST['m'])){
	$_POST['m']='main';
}

if (file_exists(BASE_DIR.APP_OPS.DIRECTORY_SEPARATOR.NAME_MDL.DIRECTORY_SEPARATOR.$_POST['m'].DIRECTORY_SEPARATOR.$_POST['f'].POSTFIX_MDL) && !is_dir(BASE_DIR.APP_OPS.DIRECTORY_SEPARATOR.NAME_MDL.DIRECTORY_SEPARATOR.$_POST['m'].DIRECTORY_SEPARATOR.$_POST['f'].POSTFIX_MDL)) {
	require BASE_DIR.APP_OPS.DIRECTORY_SEPARATOR.NAME_MDL.DIRECTORY_SEPARATOR.$_POST['m'].DIRECTORY_SEPARATOR.$_POST['f'].POSTFIX_MDL;
}else{
	$return_arr[APP_404]=URL_BASE.FILE_INF.DIRECTORY_SEPARATOR.APP_404;
}

require BASE_DIR.APP_OPS.DIRECTORY_SEPARATOR.NAME_COMM.DIRECTORY_SEPARATOR.NAME_INC.DIRECTORY_SEPARATOR.OPS_INC_RETURN.POSTFIX_INC;;
