<?php

require BASE_DIR.APP_OPS.DIRECTORY_SEPARATOR.NAME_COMM.DIRECTORY_SEPARATOR.NAME_INC.DIRECTORY_SEPARATOR.OPS_INC_VIEW.POSTFIX_INC;

$_SESSION['menu_sub_id']=$_POST['id'];

require BASE_DIR.APP_OPS.DIRECTORY_SEPARATOR.NAME_MDL.DIRECTORY_SEPARATOR.$_POST['mr'].DIRECTORY_SEPARATOR.$_POST['f'].POSTFIX_MDL;

